--PROJECT
CREATE TABLE IF NOT EXISTS ML_PROJECT(
PROJECT_ID VARCHAR(50) NOT NULL,
NAME VARCHAR(50),
DESCRIPTION VARCHAR(100),
CREATED_TIME TIMESTAMP,
CONSTRAINT PK_PROJECT PRIMARY KEY(PROJECT_ID),
);

--TENANT-PROJECTS
CREATE TABLE IF NOT EXISTS ML_TENANT_PROJECTS(
TENANT_ID VARCHAR(50) NOT NULL,
PROJECT_ID VARCHAR(50),
CONSTRAINT PK_TENANT_PROJECTS PRIMARY KEY(TENANT_ID,PROJECT_ID),
CONSTRAINT FK_PROJECT_TENANT FOREIGN KEY(PROJECT_ID) REFERENCES ML_PROJECT(PROJECT_ID) ON UPDATE
CASCADE ON DELETE CASCADE
);

--DATASET
CREATE TABLE IF NOT EXISTS ML_DATASET(
DATASET_ID VARCHAR(50) NOT NULL,
SAMPLE_POINTS OTHER,
DATASET_URL VARCHAR(300),
PROJECT_ID VARCHAR(50),
CONSTRAINT PK_DATASET PRIMARY KEY(DATASET_ID),
CONSTRAINT FK_PROJECT_DATASET FOREIGN KEY(PROJECT_ID) REFERENCES ML_PROJECT(PROJECT_ID) ON UPDATE CASCADE ON DELETE CASCADE
);


--FEATURE_DEFAULTS
CREATE TABLE IF NOT EXISTS ML_FEATURE_DEFAULTS(
DATASET_ID VARCHAR(50) NOT NULL,
FEATURE_NAME VARCHAR(100) NOT NULL,
SUMMARY CLOB,
TYPE VARCHAR(20),
IMPUTE_METHOD VARCHAR(30),
INCLUDE BOOLEAN,
CONSTRAINT PK_FEATURE_DEFAULTS PRIMARY KEY(FEATURE_NAME,DATASET_ID),
CONSTRAINT FK_DATASET_FEATURE_DEFAULTS FOREIGN KEY(DATASET_ID) REFERENCES ML_DATASET(DATASET_ID) ON
UPDATE CASCADE ON DELETE CASCADE
);

--WORKFLOW
CREATE TABLE IF NOT EXISTS ML_WORKFLOW(
WORKFLOW_ID VARCHAR(50) NOT NULL,
PARENT_WORKFLOW_ID VARCHAR(50),
PROJECT_ID VARCHAR(50) NOT NULL,
DATASET_ID VARCHAR(50) NOT NULL,
NAME VARCHAR(50),
CONSTRAINT PK_WORKFLOW PRIMARY KEY(WORKFLOW_ID),
CONSTRAINT FK_PROJECT_WORKFLOW FOREIGN KEY(PROJECT_ID) REFERENCES ML_PROJECT(PROJECT_ID) ON
UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_DATASET_WORKFLOW FOREIGN KEY(DATASET_ID) REFERENCES ML_DATASET(DATASET_ID) ON UPDATE
CASCADE ON DELETE CASCADE,
CONSTRAINT FK_PARENT_WORKFLOW FOREIGN KEY(PARENT_WORKFLOW_ID) REFERENCES ML_WORKFLOW(WORKFLOW_ID) ON
UPDATE CASCADE
);

--FEATURE_SETTINGS
CREATE TABLE IF NOT EXISTS ML_FEATURE_SETTINGS(
WORKFLOW_ID VARCHAR(50) NOT NULL,
FEATURE_NAME VARCHAR(200) NOT NULL,
TYPE VARCHAR(20),
IMPUTE_METHOD VARCHAR(30),
INCLUDE BOOLEAN,
CONSTRAINT PK_FEATURE_SETTINGS PRIMARY KEY(WORKFLOW_ID,FEATURE_NAME),
CONSTRAINT FK_WORKFLOW_FEATURE_SETTINGS FOREIGN KEY(WORKFLOW_ID) REFERENCES ML_WORKFLOW(WORKFLOW_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

--MODEL_SETTINGS
CREATE TABLE IF NOT EXISTS ML_MODEL_SETTINGS(
MODEL_SETTINGS_ID VARCHAR(50) NOT NULL,
WORKFLOW_ID VARCHAR(50) NOT NULL,
ALGORITHM_CLASS VARCHAR(20) NOT NULL,
ALGORITHM_NAME VARCHAR(50) NOT NULL,
RESPONSE VARCHAR(200) NOT NULL,
TRAIN_DATA_FRACTION DOUBLE,
HYPER_PARAMETERS OTHER,
CONSTRAINT PK_FEATURE PRIMARY KEY(MODEL_SETTINGS_ID),
CONSTRAINT FK_WORKFLOW_MODEL_SETTINGS FOREIGN KEY(WORKFLOW_ID) REFERENCES ML_WORKFLOW(WORKFLOW_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

--MODEL
CREATE TABLE IF NOT EXISTS ML_MODEL(
MODEL_ID VARCHAR(50) NOT NULL,
WORKFLOW_ID VARCHAR(50) NOT NULL,
MODEL_EXECUTION_START_TIME TIMESTAMP,
MODEL_EXECUTION_END_TIME TIMESTAMP,
MODEL OTHER,
MODEL_SUMMARY OTHER,
CONSTRAINT PK_MODEL PRIMARY KEY(MODEL_ID),
CONSTRAINT FK_WORKFLOW_MODEL FOREIGN KEY(WORKFLOW_ID) REFERENCES ML_WORKFLOW(WORKFLOW_ID) ON UPDATE
CASCADE ON DELETE CASCADE
);

--CONFIGURATION
CREATE TABLE IF NOT EXISTS ML_CONFIGURATION (
DATASET_UPLOADING_DIR VARCHAR(100),
DATASET_IN_MEM_THRESHOLD DOUBLE,
DATASET_UPLOADING_LIMIT DOUBLE,
INTERVALS INTEGER,
SEPARATOR VARCHAR(2)
);

--ALGORITHM
CREATE TABLE IF NOT EXISTS ML_ALGORITHM(
NAME VARCHAR(50)  NOT NULL,
TYPE VARCHAR(20),
INTERPRETABILITY INTEGER,
SCALABILITY INTEGER,
MULTICOLLINEARITY INTEGER,
DIMENSIONALITY INTEGER,
HYPERPARAMETERS VARCHAR(500),
CONSTRAINT PK_ALGORITHM PRIMARY KEY(NAME)
);


INSERT INTO  ML_Algorithm VALUES 
('LINEAR_REGRESSION','Numerical_Prediction',5,5,1,5,'{"parameters":[{"parameter":"Iterations","value":100}]}'),
('LOGISTIC_REGRESSION','Classification',3,5,1,5,'{"parameters":[{"parameter":"Iterations","value":100},{"parameter":"Learning_Rate","value":0.001},{"parameter":"Reg_Type","value":"L1"},{"parameter":"Reg_Parameter","value":0.001},{"parameter":"SGD_Data_Fraction","value":1.0}]}'),
('SVM','Classification',1,1,5,5,'{"parameters":[{"parameter":"Iterations","value":100},{"parameter":"Reg_Parameter","value":0.001}]}'),
('DECISION_TREE','Classification',5,4,5,3,'{"parameters":[{"parameter":"Num_Classes","value":2},{"parameter":"Max_Depth","value":5},{"parameter":"Max_Bins","value":100},{"parameter":"Impurity","value":"gini"}]}'),
('NAIVE_BAYES','Classification',3,5,1,5,'{"parameters":[{"parameter":"Lambda","value":1.0}]}'),
('K_MEANS','Clustering',5,2,5,2,'{"parameters":[{"parameter":"Iterations","value":20},{"parameter":"Num_Clusters","value":3}]}');

INSERT INTO ML_CONFIGURATION VALUES ('/Users/lochana/temp',1024,20971520,20,',');
