--PROJECT
CREATE TABLE IF NOT EXISTS ML_PROJECT(
PROJECT_ID VARCHAR(50) NOT NULL,
NAME VARCHAR(50),
DESCRIPTION VARCHAR(100),
CREATED_TIME TIMESTAMP,
CONSTRAINT PK_PROJECT PRIMARY KEY(PROJECT_ID),
);

--TENANT-PROJECTS
CREATE TABLE IF NOT EXISTS ML_TENANT_PROJECTS(
TENANT_ID VARCHAR(50) NOT NULL,
PROJECT_ID VARCHAR(50),
CONSTRAINT PK_TENANT_PROJECTS PRIMARY KEY(TENANT_ID,PROJECT_ID),
CONSTRAINT FK_PROJECT_TENANT FOREIGN KEY(PROJECT_ID) REFERENCES ML_PROJECT(PROJECT_ID) ON UPDATE
CASCADE ON DELETE CASCADE
);

--DATASET
CREATE TABLE IF NOT EXISTS ML_DATASET(
DATASET_ID VARCHAR(50) NOT NULL,
SAMPLE_POINTS OTHER,
DATASET_URL VARCHAR(300),
PROJECT_ID VARCHAR(50),
CONSTRAINT PK_DATASET PRIMARY KEY(DATASET_ID),
CONSTRAINT FK_PROJECT_DATASET FOREIGN KEY(PROJECT_ID) REFERENCES ML_PROJECT(PROJECT_ID) ON UPDATE CASCADE ON DELETE CASCADE
);


--FEATURE_DEFAULTS
CREATE TABLE IF NOT EXISTS ML_FEATURE_DEFAULTS(
DATASET_ID VARCHAR(50) NOT NULL,
FEATURE_INDEX INT,
FEATURE_NAME VARCHAR(100) NOT NULL,
SUMMARY CLOB,
TYPE VARCHAR(20),
IMPUTE_METHOD VARCHAR(30),
INCLUDE BOOLEAN,
CONSTRAINT PK_FEATURE_DEFAULTS PRIMARY KEY(FEATURE_NAME,DATASET_ID),
CONSTRAINT FK_DATASET_FEATURE_DEFAULTS FOREIGN KEY(DATASET_ID) REFERENCES ML_DATASET(DATASET_ID) ON
UPDATE CASCADE ON DELETE CASCADE
);

--WORKFLOW
CREATE TABLE IF NOT EXISTS ML_WORKFLOW(
WORKFLOW_ID VARCHAR(50) NOT NULL,
PARENT_WORKFLOW_ID VARCHAR(50),
PROJECT_ID VARCHAR(50) NOT NULL,
DATASET_ID VARCHAR(50) NOT NULL,
NAME VARCHAR(50),
CONSTRAINT PK_WORKFLOW PRIMARY KEY(WORKFLOW_ID),
CONSTRAINT FK_PROJECT_WORKFLOW FOREIGN KEY(PROJECT_ID) REFERENCES ML_PROJECT(PROJECT_ID) ON
UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_DATASET_WORKFLOW FOREIGN KEY(DATASET_ID) REFERENCES ML_DATASET(DATASET_ID) ON UPDATE
CASCADE ON DELETE CASCADE,
CONSTRAINT FK_PARENT_WORKFLOW FOREIGN KEY(PARENT_WORKFLOW_ID) REFERENCES ML_WORKFLOW(WORKFLOW_ID) ON
UPDATE CASCADE
);

--FEATURE_SETTINGS
CREATE TABLE IF NOT EXISTS ML_FEATURE_SETTINGS(
WORKFLOW_ID VARCHAR(50) NOT NULL,
FEATURE_NAME VARCHAR(200) NOT NULL,
FEATURE_INDEX INT,
TYPE VARCHAR(20),
IMPUTE_METHOD VARCHAR(30),
INCLUDE BOOLEAN,
CONSTRAINT PK_FEATURE_SETTINGS PRIMARY KEY(WORKFLOW_ID,FEATURE_NAME),
CONSTRAINT FK_WORKFLOW_FEATURE_SETTINGS FOREIGN KEY(WORKFLOW_ID) REFERENCES ML_WORKFLOW(WORKFLOW_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

--MODEL_SETTINGS
CREATE TABLE IF NOT EXISTS ML_MODEL_SETTINGS(
MODEL_SETTINGS_ID VARCHAR(50) NOT NULL,
WORKFLOW_ID VARCHAR(50) NOT NULL,
ALGORITHM_CLASS VARCHAR(20) NOT NULL,
ALGORITHM_NAME VARCHAR(50) NOT NULL,
RESPONSE VARCHAR(200) NOT NULL,
TRAIN_DATA_FRACTION DOUBLE,
HYPER_PARAMETERS OTHER,
CONSTRAINT PK_FEATURE PRIMARY KEY(MODEL_SETTINGS_ID),
CONSTRAINT FK_WORKFLOW_MODEL_SETTINGS FOREIGN KEY(WORKFLOW_ID) REFERENCES ML_WORKFLOW(WORKFLOW_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

--MODEL
CREATE TABLE IF NOT EXISTS ML_MODEL(
MODEL_ID VARCHAR(50) NOT NULL,
WORKFLOW_ID VARCHAR(50) NOT NULL,
MODEL_EXECUTION_START_TIME TIMESTAMP,
MODEL_EXECUTION_END_TIME TIMESTAMP,
MODEL OTHER,
MODEL_SUMMARY OTHER,
CONSTRAINT PK_MODEL PRIMARY KEY(MODEL_ID),
CONSTRAINT FK_WORKFLOW_MODEL FOREIGN KEY(WORKFLOW_ID) REFERENCES ML_WORKFLOW(WORKFLOW_ID) ON UPDATE
CASCADE ON DELETE CASCADE
);
