--** PROJECT **
CREATE TABLE IF NOT EXISTS ML_PROJECT(
ID UUID NOT NULL,
NAME VARCHAR(50),
DESCRIPTION VARCHAR(100),
CREATED_TIME TIMESTAMP,
CONSTRAINT PK_PROJECT PRIMARY KEY(ID),
);

--** USER-PROJECTS **
CREATE TABLE IF NOT EXISTS ML_USER_PROJECTS(
USERNAME VARCHAR(100) NOT NULL,
PROJECT UUID,
CONSTRAINT PK_DATASETML_USER_PROJECTS  PRIMARY KEY(USERNAME,PROJECT),
CONSTRAINT FK_PROJECT_USER FOREIGN KEY(PROJECT) REFERENCES ML_PROJECT(ID) ON UPDATE CASCADE ON DELETE CASCADE
);


--**DATASET***
CREATE TABLE IF NOT EXISTS ML_DATASET(
ID UUID NOT NULL,
SAMPLE_POINTS OTHER,
URI VARCHAR(300),
PROJECT UUID,
CONSTRAINT PK_DATASET PRIMARY KEY(ID),
CONSTRAINT FK_PROJECT_DATASET FOREIGN KEY(PROJECT) REFERENCES ML_PROJECT(ID) ON UPDATE CASCADE ON DELETE CASCADE
);


--**FEATURE**
CREATE TABLE IF NOT EXISTS ML_FEATURE(
NAME VARCHAR(100),
DATASET UUID,
TYPE VARCHAR(20),
SUMMARY CLOB,
IMPUTE_METHOD VARCHAR(30),
IMPORTANT BOOLEAN,
CONSTRAINT PK_FEATURE PRIMARY KEY(NAME,DATASET),
CONSTRAINT FK_DATASET_FEATURE FOREIGN KEY(DATASET) REFERENCES ML_DATASET(ID) ON UPDATE CASCADE ON DELETE CASCADE
);



--**PROCESS**
CREATE TABLE IF NOT EXISTS ML_PROCESS(
ID UUID NOT NULL,
PROJECT UUID,
NAME VARCHAR(50),
DESCRIPTION VARCHAR(100),
CONSTRAINT PK_PROCESS PRIMARY KEY(ID),
CONSTRAINT FK_PROJECT_PROCESS FOREIGN KEY(PROJECT) REFERENCES ML_PROJECT(ID) ON UPDATE CASCADE ON DELETE CASCADE
);


--**MODEL**
CREATE TABLE IF NOT EXISTS ML_MODEL(
ID UUID NOT NULL,
PROCESS UUID,
MODEL OTHER,
MODEL_SUMMARY OTHER,
CONSTRAINT PK_MODEL PRIMARY KEY(ID),
CONSTRAINT FK_PROCESS_MODEL FOREIGN KEY(PROCESS) REFERENCES ML_PROCESS(ID) ON UPDATE CASCADE ON DELETE CASCADE
);


--**EXECUTION**
CREATE TABLE IF NOT EXISTS ML_EXECUTION(
ID UUID NOT NULL,
MODEL UUID,
PROCESS UUID,
START_TIME TIMESTAMP,
END_TIME TIMESTAMP,
CONSTRAINT PK_EXECUTION PRIMARY KEY(ID),
CONSTRAINT FK_MODEL_EXECUTION FOREIGN KEY(MODEL) REFERENCES ML_MODEL(ID) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_PROCESS_EXECUTION FOREIGN KEY(PROCESS) REFERENCES ML_PROCESS(ID) ON UPDATE CASCADE ON DELETE CASCADE
);


--**CONFIGURATION**
CREATE TABLE IF NOT EXISTS ML_CONFIGURATION (
DATASET_UPLOADING_DIR  VARCHAR(100),
DATASET_IN_MEM_THRESHOLD  DOUBLE,
DATASET_UPLOADING_LIMIT DOUBLE,
INTERVALS INTEGER,
SEPARATOR VARCHAR(2)
);


--**ALGORITHM**
CREATE TABLE IF NOT EXISTS ML_ALGORITHM(
NAME VARCHAR(50)  NOT NULL,
TYPE VARCHAR(20),
INTERPRETABILITY INTEGER,
SCALABILITY INTEGER,
MULTICOLLINEARITY INTEGER,
DIMENSIONALITY INTEGER,
HYPERPARAMETERS VARCHAR(500),
CONSTRAINT PK_ALGORITHM PRIMARY KEY(NAME)
);


INSERT INTO  ML_Algorithm VALUES 
('LINEAR_REGRESSION','Numerical_Prediction',5,5,1,5,'{"parameters":[{"parameter":"Iterations","value":100}]}'),
('LOGISTIC_REGRESSION','Classification',3,5,1,5,'{"parameters":[{"parameter":"Iterations","value":100},{"parameter":"Learning_Rate","value":0.001},{"parameter":"Reg_Type","value":"L1"},{"parameter":"Reg_Parameter","value":0.001},{"parameter":"SGD_Data_Fraction","value":1.0}]}'),
('SVM','Classification',1,1,5,5,'{"parameters":[{"parameter":"Iterations","value":100},{"parameter":"Reg_Parameter","value":0.001}]}'),
('DECISION_TREE','Classification',5,4,5,3,'{"parameters":[{"parameter":"Num_Classes","value":2},{"parameter":"Max_Depth","value":5},{"parameter":"Max_Bins","value":100},{"parameter":"Impurity","value":"gini"}]}'),
('NAIVE_BAYES','Classification',3,5,1,5,'{"parameters":[{"parameter":"Lambda","value":1.0}]}'),
('K_MEANS','Clustering',5,2,5,2,'{"parameters":[{"parameter":"Iterations","value":20},{"parameter":"Num_Clusters","value":3}]}');

INSERT INTO ML_CONFIGURATION VALUES ('/Users/lochana/temp/',1024,20971520,20,',');
