--DATASET
CREATE TABLE IF NOT EXISTS ML_DATASET(
DATASET_ID BIGINT AUTO_INCREMENT,
NAME VARCHAR(50),
TENANT_ID VARCHAR(50),
USERNAME VARCHAR(50),
COMMENTS CLOB,
SOURCE_TYPE VARCHAR(50),
TARGET_TYPE VARCHAR(50),
DATA_TYPE VARCHAR(50),
CONSTRAINT PK_DATASET PRIMARY KEY(DATASET_ID),
);

--DATASET_VERSION
CREATE TABLE IF NOT EXISTS ML_DATASET_VERSION(
DATASET_VERSION_ID BIGINT AUTO_INCREMENT,
DATASET_ID BIGINT,
TENANT_ID VARCHAR(50),
VERSION VARCHAR(50),
CONSTRAINT PK_DATASET_VERSION PRIMARY KEY(DATASET_VERSION_ID),
CONSTRAINT FK_DATASET_DATASET_VERSION FOREIGN KEY(DATASET_ID) REFERENCES ML_DATASET(DATASET_ID)
ON UPDATE CASCADE ON DELETE CASCADE
);

--FEATURE_DEFAULTS
CREATE TABLE IF NOT EXISTS ML_FEATURE_DEFAULTS(
FEATURE_ID BIGINT AUTO_INCREMENT,
DATASET_VERSION_ID BIGINT,
FEATURE_INDEX INT,
FEATURE_NAME VARCHAR(100) NOT NULL,
SUMMARY CLOB,
TYPE VARCHAR(20),
CONSTRAINT PK_FEATURE_DEFAULTS PRIMARY KEY(FEATURE_ID),
CONSTRAINT FK_DATASET_VERSION_FEATURE_DEFAULTS FOREIGN KEY(DATASET_VERSION_ID) REFERENCES ML_DATASET_VERSION(DATASET_VERSION_ID)
ON UPDATE CASCADE ON DELETE CASCADE
);

--VALUE_SET
CREATE TABLE IF NOT EXISTS ML_VALUE_SET(
VALUE_SET_ID BIGINT AUTO_INCREMENT,
DATASET_VERSION_ID BIGINT,
TENANT_ID VARCHAR(50),
URI VARCHAR(300),
SAMPLE_POINTS OTHER,
CONSTRAINT FK_DATASET_VERSION_VALUE_SET FOREIGN KEY(DATASET_VERSION_ID) REFERENCES ML_DATASET_VERSION(DATASET_VERSION_ID)
ON UPDATE CASCADE ON DELETE CASCADE
);