# DATASET
CREATE TABLE IF NOT EXISTS ML_DATASET_SCHEMA(
DATASET_SCHEMA_ID BIGINT AUTO_INCREMENT,
NAME VARCHAR(50),
TENANT_ID INT,
USERNAME VARCHAR(50),
COMMENTS TEXT,
SOURCE_TYPE VARCHAR(50),
TARGET_TYPE VARCHAR(50),
DATA_TYPE VARCHAR(50),
CONSTRAINT PK_DATASET_SCHEMA PRIMARY KEY(DATASET_SCHEMA_ID)
);

# FEATURE_DEFAULTS
CREATE TABLE IF NOT EXISTS ML_FEATURE_DEFAULTS(
DATASET_SCHEMA_ID BIGINT,
FEATURE_INDEX INT,
FEATURE_NAME VARCHAR(100) NOT NULL,
TYPE VARCHAR(20),
CONSTRAINT FK_DATASET_SCHEMA_FEATURE_DEFAULTS FOREIGN KEY(DATASET_SCHEMA_ID) REFERENCES ML_DATASET_SCHEMA(DATASET_SCHEMA_ID)
ON UPDATE CASCADE ON DELETE CASCADE
);

# DATASET_VERSION
CREATE TABLE IF NOT EXISTS ML_DATASET_VERSION(
DATASET_VERSION_ID BIGINT AUTO_INCREMENT,
DATASET_SCHEMA_ID BIGINT,
NAME VARCHAR(50),
VERSION VARCHAR(50),
TENANT_ID INT,
USERNAME VARCHAR(50),
URI VARCHAR(300),
SAMPLE_POINTS BLOB,
CONSTRAINT PK_DATASET_VERSION PRIMARY KEY(DATASET_VERSION_ID),
CONSTRAINT FK_DATASET_SCHEMA_DATASET_VERSION FOREIGN KEY(DATASET_SCHEMA_ID) REFERENCES ML_DATASET_SCHEMA(DATASET_SCHEMA_ID)
ON UPDATE CASCADE ON DELETE CASCADE
);

# FEATURE_SUMMARY
CREATE TABLE IF NOT EXISTS ML_FEATURE_SUMMARY(
  FEATURE_NAME VARCHAR(100),
  DATASET_VERSION_ID BIGINT,
  SUMMARY TEXT,
  CONSTRAINT FK_DATASET_SCHEMA_FEATURE_SUMMARY FOREIGN KEY(FEATURE_NAME) REFERENCES ML_FEATURE_DEFAULTS(FEATURE_NAME)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT FK_DATASET_VERSION_FEATURE_SUMMARY FOREIGN KEY(DATASET_VERSION_ID) REFERENCES ML_DATASET_VERSION(DATASET_VERSION_ID)
    ON UPDATE CASCADE ON DELETE CASCADE
);

# DATA_SOURCE
CREATE TABLE IF NOT EXISTS ML_DATA_SOURCE(
DATASET_VERSION_ID BIGINT,
TENANT_ID INT,
USERNAME VARCHAR(50),
`KEY` VARCHAR(50),
VALUE VARCHAR(50),
CONSTRAINT FK_VALUE_SET_DATA_SOURCE FOREIGN KEY(DATASET_VERSION_ID) REFERENCES ML_DATASET_VERSION(DATASET_VERSION_ID)
ON UPDATE CASCADE ON DELETE CASCADE
);

# PROJECT
CREATE TABLE IF NOT EXISTS ML_PROJECT(
PROJECT_ID BIGINT AUTO_INCREMENT,
NAME VARCHAR(50),
DESCRIPTION VARCHAR(100),
TENANT_ID INT,
USERNAME VARCHAR(5),
CREATED_TIME TIMESTAMP,
CONSTRAINT PK_PROJECT PRIMARY KEY(PROJECT_ID,TENANT_ID)
);

# ANALYSIS
CREATE TABLE IF NOT EXISTS ML_ANALYSIS(
ANALYSIS_ID BIGINT AUTO_INCREMENT,
PROJECT_ID BIGINT,
NAME VARCHAR(50),
TENANT_ID INT,
COMMENTS TEXT,
CONSTRAINT PK_ANALYSIS PRIMARY KEY(ANALYSIS_ID),
CONSTRAINT FK_PROJECT_ANALYSIS FOREIGN KEY(PROJECT_ID) REFERENCES ML_PROJECT(PROJECT_ID)
ON UPDATE CASCADE ON DELETE CASCADE
);

# MODEL
CREATE TABLE IF NOT EXISTS ML_MODEL(
MODEL_ID BIGINT AUTO_INCREMENT,
ANALYSIS_ID BIGINT,
VALUE_SET_ID BIGINT,
TENANT_ID INT,
USERNAME VARCHAR(50),
CREATED_TIME TIMESTAMP,
CONSTRAINT PK_MODEL PRIMARY KEY(MODEL_ID),
CONSTRAINT FK_ANALYSIS_MODEL FOREIGN KEY(ANALYSIS_ID) REFERENCES ML_ANALYSIS(ANALYSIS_ID),
CONSTRAINT FK_VALUE_SET_MODEL FOREIGN KEY(VALUE_SET_ID) REFERENCES ML_VALUE_SET(VALUE_SET_ID)
ON UPDATE CASCADE ON DELETE CASCADE
);

# MODEL_CONFIGURATION
CREATE TABLE IF NOT EXISTS ML_MODEL_CONFIGURATION(
MODEL_ID BIGINT,
TENANT_ID INT,
USERNAME VARCHAR(50),
`KEY` VARCHAR(50),
VALUE VARCHAR(50),
TYPE VARCHAR(50),
CONSTRAINT FK_MODEL_MODEL_CONFIGURATION FOREIGN KEY(MODEL_ID) REFERENCES ML_MODEL(MODEL_ID)
ON UPDATE CASCADE ON DELETE CASCADE
);

# FEATURE_CUSTOMIZED
CREATE TABLE IF NOT EXISTS ML_FEATURE_CUSTOMIZED(
MODEL_ID BIGINT,
TENANT_ID INT,
FEATURE_NAME VARCHAR(50),
FEATURE_TYPE VARCHAR(50),
IMPUTE_OPTION VARCHAR(50),
INCLUSION BOOLEAN,
LAST_MODIFIED_USER VARCHAR(50),
LAST_MODIFIED_TIME TIMESTAMP,
CONSTRAINT FK_MODEL_FEATURE_CUSTOMIZED FOREIGN KEY(MODEL_ID) REFERENCES ML_MODEL(MODEL_ID)
ON UPDATE CASCADE ON DELETE CASCADE
);

# HYPER_PARAMETER
CREATE TABLE IF NOT EXISTS ML_HYPER_PARAMETER(
MODEL_ID BIGINT,
NAME VARCHAR(50),
TENANT_ID INT,
VALUE VARCHAR(50),
LAST_MODIFIED_USER VARCHAR(50),
LAST_MODIFIED_TIME TIMESTAMP,
CONSTRAINT FK_MODEL_HYPER_PARAMETER FOREIGN KEY(MODEL_ID) REFERENCES ML_MODEL(MODEL_ID)
ON UPDATE CASCADE ON DELETE CASCADE
);